[mypy]
strict = True
disallow_any_explicit = True
files = agent/

[mypy-agent.finance_api_client]
ignore_errors = True

[mypy-agent.finance_api_client.*]
ignore_errors = True

[mypy-agent.config.settings]
disallow_any_explicit = False
