#!/usr/bin/env bash
# ==============================================================================
# bootstrap-keys.sh — Idempotent RS256 keypair generator for M2M JWT auth
# Usage: scripts/bootstrap-keys.sh
#
# If .env.local already contains a valid LUCI_M2M_PRIVATE_KEY_PEM, exits 0.
# Otherwise generates a 2048-bit RSA keypair, writes PEM-encoded halves
# and a stable kid into .env.local. (FR-021, R-5)
# ==============================================================================
set -euo pipefail

ENV_FILE="${1:-.env.local}"

# Check if a valid key already exists
if [ -f "$ENV_FILE" ]; then
    EXISTING_KEY=$(grep '^LUCI_M2M_PRIVATE_KEY_PEM=' "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2-)
    if [ -n "$EXISTING_KEY" ] && [ "$EXISTING_KEY" != "REPLACE_ME_WITH_make_bootstrap" ]; then
        # Attempt to parse it — if openssl can read it, it's valid
        if echo "$EXISTING_KEY" | sed 's/\\n/\n/g' | openssl rsa -check -noout 2>/dev/null; then
            echo "✓ Valid M2M keypair already present in $ENV_FILE — skipping generation."
            exit 0
        else
            echo "⚠ LUCI_M2M_PRIVATE_KEY_PEM in $ENV_FILE looks malformed. Regenerating..."
            # Remove old key lines so we can write fresh ones
            sed -i '/^LUCI_M2M_PRIVATE_KEY_PEM=/d' "$ENV_FILE"
            sed -i '/^LUCI_M2M_PUBLIC_KEY_PEM=/d' "$ENV_FILE"
            sed -i '/^LUCI_M2M_KID=/d' "$ENV_FILE"
        fi
    fi
fi

echo "→ Generating 2048-bit RS256 keypair for M2M JWT auth..."

# Generate keypair
PRIVATE_KEY_FILE=$(mktemp)
PUBLIC_KEY_FILE=$(mktemp)
trap 'rm -f "$PRIVATE_KEY_FILE" "$PUBLIC_KEY_FILE"' EXIT

openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -outform PEM -out "$PRIVATE_KEY_FILE" 2>/dev/null
openssl rsa -in "$PRIVATE_KEY_FILE" -pubout -outform PEM -out "$PUBLIC_KEY_FILE" 2>/dev/null

# Encode PEM as single-line with literal \n
PRIVATE_PEM=$(cat "$PRIVATE_KEY_FILE" | tr '\n' '|' | sed 's/|/\\n/g')
PUBLIC_PEM=$(cat "$PUBLIC_KEY_FILE" | tr '\n' '|' | sed 's/|/\\n/g')

# Stable kid: luci-m2m-<unix-epoch>
KID="luci-m2m-$(date +%s)"

# Remove old placeholder values if present
if [ -f "$ENV_FILE" ]; then
    sed -i '/^LUCI_M2M_PRIVATE_KEY_PEM=/d' "$ENV_FILE"
    sed -i '/^LUCI_M2M_PUBLIC_KEY_PEM=/d' "$ENV_FILE"
    sed -i '/^LUCI_M2M_KID=/d' "$ENV_FILE"
fi

# Append key material
{
    echo ""
    echo "# --- M2M JWT Keys (generated by bootstrap-keys.sh) ---"
    echo "LUCI_M2M_KID=$KID"
    echo "LUCI_M2M_PRIVATE_KEY_PEM=$PRIVATE_PEM"
    echo "LUCI_M2M_PUBLIC_KEY_PEM=$PUBLIC_PEM"
} >> "$ENV_FILE"

echo "✓ M2M keypair written to $ENV_FILE (kid=$KID)"
